name: responsive_grid
description: Responsive Grid Layout and List for Flutter
version: 2.1.1
homepage: https://github.com/muhammad369/ResponsiveGrid_Flutter

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
